config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :user do
    resources :articles
  end

  get 'home/index'
  devise_scope :user do
    root :to => "home#index"
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :delete]

  def index
    
  end

  def show
  end

  def new
  end

  def create
    user = User.find(paramas[:user_id])
    User.articles.create(params.require(:article).permit(:title, :content))
    redirect_to user(users)
  end

  def edit
  end

  def delete
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/delete.html.slim
h1 Articles#delete
p Find me in app/views/articles/delete.html.slim

app/views/articles/edit.html.slim
h1 Articles#edit
p Find me in app/views/articles/edit.html.slim

app/views/articles/index.html.slim
h1 Articles#index
p Find me in app/views/articles/index.html.slim

app/views/articles/new.html.slim
h1 記事登録

= form_for @article do |f| 
  = f.label :title 
  = f.text_field :title
  = f.label :content
  = f.text_field :content
  = f.submit

app/views/articles/show.html.slim
h1 Articles#show
p Find me in app/views/articles/show.html.slim

app/views/home/index.html.slim
h1
  'Home#index
- if user_signed_in? 
  'Logged as
  strong
    = current_user.email
    = link_to "Settings", edit_user_registration_path, :class => "navbar-link" 
    '|
    = link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" 
    '|

  = link_to "記事を投稿する", new_user_article_path(current_user.id)  

- else
  = link_to "Sign up", new_user_registration_path, :class => 'navbar-link' 
  br
  = link_to "Login", new_user_session_path, :class => 'navbar-link'

- @articles.each do |article|
  = article.title

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | WebArticleApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield
    - if notice 
      p 
        class="alert alert-success"
        = notice
    - if alert 
      p class="alert alert-danger"
      = alert